---
name: Benchmark
on: workflow_dispatch
jobs:
  benchmark:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install . matplotlib pycrypto rc4
    - run: nice -19 python benchmark.py -o benchmark.svg
    - uses: actions/upload-artifact@v2
      with:
        name: benchmark
        path: benchmark.svg
    - uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: '991d0c197e1cb62eec81edec65363187'
        file_path: benchmark.svg
