---
name: Release
on:
  push:
    tags:
    - '*.*.*'
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Do not deploy to PyPI
        default: true
jobs:
  build-sdist:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: python setup.py sdist --verbose
    - uses: actions/upload-artifact@v3
      with:
        path: dist/arc4-*.tar.gz
  build-wheels:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os:
        - macOS-11
        - windows-2019
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - 'pypy-3.7'
        - 'pypy-3.8'
        - 'pypy-3.9'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "${{ matrix.python-version }}"
    - run: pip install wheel
    - run: python setup.py bdist_wheel
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*whl
  build-manylinux-wheels:
    runs-on: ubuntu-20.04
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - cp37-cp37m
        - cp38-cp38
        - cp39-cp39
        - cp310-cp310
        - cp311-cp311
        - pp37-pypy37_pp73
        - pp38-pypy38_pp73
        - pp39-pypy39_pp73
    steps:
    - uses: actions/checkout@v3
    - run: /opt/python/${{ matrix.python-version }}/bin/pip wheel .
    - run: auditwheel repair arc4-*-linux*.whl --plat manylinux_2_28_x86_64
    - uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/arc4-*-manylinux*.whl
  deploy:
    if: ${{ github.event_name == 'push' || !github.event.inputs.dry-run }}
    needs:
    - build-sdist
    - build-wheels
    - build-manylinux-wheels
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install twine
    - uses: actions/download-artifact@v3
    - run: twine upload --verbose artifact/*
      env:
        TWINE_NON_INTERACTIVE: 1
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
